substitutions:
  name: "robot"
  friendly_name: "Robot"

packages:
  device_base: !include modules/device_base.yaml
  wifi: !include modules/wifi.yaml

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:

ota:
  - platform: esphome
    password: !secret ota_password